version: "3.8"

services:
  web:
    image: php:8.2-apache # PHP with Apache
    container_name: php-web-1
    ports:
      - "8080:80" # Map port 8080 on your machine to port 80 in the container
    volumes:
      - ./src:/var/www/html # Map the src folder to the web server's root directory
